### ISSUE TITLE
【報告】Config設定エラーとその対処法について

### ISSUE THREAD

**Issue by YukanaHitsugi** [NUROKU/DavinciResolve_VoiceAutoTool#16]
はじめまして。
VoiceAutoTool使わせていただきました。大変便利で助かっております。

本題ですが、VoiceAutoToolのConfig設定が上手くいかないエラーが発生しました。

【発生条件】
・"C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Config" が空であること。

【エラー内容】
- Config設定を保存するために「保存」ボタンを押しても、「保存完了！！！！」という文字列も表示されません。
- Configフォルダ内にも何のファイルも生成されません。
- コンソールにエラーメッセージが表示されます。（添付画像参照）

![VoiceAutoUtil_Configエラー](https://user-images.githubusercontent.com/92202591/136648692-e902ef72-7998-415c-bcfb-bdfaab8f0a5d.png)

【対処法】
- "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Config" の下に"VoiceAutoTool_Config"フォルダを作成する。

（VoiceAutoTool_Configフォルダ内にもAutoTool_Config.luaファイルが生成されたことを確認しており、その後は他スクリプトも正常に動作しました。）
![VoiceAutoUtil_Configエラー_解決](https://user-images.githubusercontent.com/92202591/136649035-66a69cbe-4587-4f93-ad5f-4ffc9503c1f2.png)

本スクリプトを使用する上でConfig設定は重要な部分ですが、インストール手順にはVoiceAutoTool_Configフォルダについて何も記述されていないようです。
そのため、インストール手順への追記をお願いしたいです。
（実際には記述されていて、私が見落としているだけでしたら大変申し訳ありません）

以上、よろしくお願いいたします。

**Comment by NUROKU** [comment]
はじめまして。
VoiceAutoToolをご利用いただき、ありがとうございます。

> 本スクリプトを使用する上でConfig設定は重要な部分ですが、インストール手順にはVoiceAutoTool_Configフォルダについて何も記述されていないようです。
> そのため、インストール手順への追記をお願いしたいです。

インストール手順にVoiceAutoTool_Configフォルダを置く手順を追加し、VoiceAutoTool(proto)_v0.5.1の再リリースを行いました。
元々Configフォルダ下にAutoTool_Config.luaが置かれる仕様だったのですが、他のスクリプトと混ざる可能性があったのでVoiceAutoTool_Configフォルダを間に挟むアップデートを行いました。その時に手順の追加修正を忘れていたみたいです…ｱｧｰ

本報告が無ければ一生このままだったかと思います。報告していただきありがとうございました！
